### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by liamtoney** [Donavin97/SeismicSonify#1]
Hi @Donavin97, it's great to see someone using and modifying _sonify_. Would you mind adding an attribution/link to the original _sonify_ repo at https://github.com/liamtoney/sonify to your [`README.rst`](https://github.com/Donavin97/SeismicSonify/blob/master/README.rst)? Since this isn't a fork of that repo, the connection is not as clear. Thanks for your consideration.

**Comment by Donavin97** [comment]
Hi @liamtoney 
Thanks for bringing this to my attention.
I'll gladly update the readme to atribute you.
I also wanted to thank you for creating such an amazing project. 
I am a blind seismologist, I use your tool daily to review waveforms by ear to confirm seismic events. 
If you have any questions, please feel free to ask.

**Comment by liamtoney** [comment]
Thank you, @Donavin97, and I am so happy to hear that this tool has been useful for you!
